basePath: /
definitions:
  main.Photo:
    properties:
      cid:
        type: string
      id:
        type: integer
      name:
        type: string
      owner:
        $ref: '#/definitions/main.User'
    type: object
  main.User:
    properties:
      apikey:
        type: string
      email:
        type: string
      handle:
        type: string
      id:
        type: integer
    type: object
info:
  contact: {}
  title: People API
  version: "2.0"
paths:
  /:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: API greeting message
  /photo:
    post:
      consumes:
      - application/json
      parameters:
      - description: name of the photo
        in: body
        name: name
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/main.Photo'
      summary: Upload a new Photo
  /photo/{cid}:
    get:
      parameters:
      - description: first name
        in: query
        name: cid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Download existing photo
schemes:
- http
swagger: "2.0"
